server:
  port: ${PORT:5001}

base-url: /api

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME}
    token: ${TELEGRAM_BOT_TOKEN}

spring:
  application:
    name: spring_ts_app

    liquibase:
      #    enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml

    mvc:
      hiddenmethod:
        filter:
          enabled: true

    jpa:
      hibernate:
        ddl-auto: create-drop
