server:
  port: ${PORT:5001}

base-url: /api

telegram:
  bot:
    name: IBRYouTrackBot
    token: 5396094706:AAEexDzbX8yWD2N5HLVNTWIAmT0qJwGL7WU
    chatId: -809118194

spring:
  application:
    name: spring_ts_app

    liquibase:
      #    enabled: true
      change-log: classpath:db/changelog/db.changelog-master.yaml

    mvc:
      hiddenmethod:
        filter:
          enabled: true

    jpa:
      hibernate:
        ddl-auto: create-drop